### ISSUE TITLE
 `useClickOutside` fails when element is partially off the page

### ISSUE THREAD

**Issue by seanfcarroll** [stimulus-use/stimulus-use#103]
Great library, thank you @adrienpoly ! 

When the `useClickOutside` element is partially off the page (eg: a drop down menu), the event does not fire.

**This works**

<img width="1417" alt="Screen Shot 2021-01-16 at 12 10 39" src="https://user-images.githubusercontent.com/11340230/104810350-3c493700-57f4-11eb-946d-1cc96e7650a0.png">

**This doesn't work (doesn't trigger an event)**

<img width="1415" alt="Screen Shot 2021-01-16 at 12 10 48" src="https://user-images.githubusercontent.com/11340230/104810352-40755480-57f4-11eb-981b-b2f32fc9cb0f.png">

**Comment by adrienpoly** [comment]
There is an option visibleOnly (default true). The intent was to prevent triggering the event if the element is not in the view port. But there is a bug as partiality in the viewport should trigger an event. 

For now you can probably use je option to disable this behaviour

**Comment by seanfcarroll** [comment]
That fixed it, thanks a lot @adrienpoly !

For other people looking for this, here is my controller (I'm using the CSS checkbox method to make a menu appear).

```js
import { Controller } from 'stimulus';
import { useClickOutside } from 'stimulus-use'

export default class extends Controller {
  static targets = [ 'checkbox', 'list' ]

  connect() {
    useClickOutside(this, {element: this.listTarget, onlyVisible: false})
  }

  clickOutside(event) {
    if(!this.element.contains(event.srcElement)) {
      this.checkboxTarget.checked = false
    }
  }
}
```

**Comment by adrienpoly** [comment]
@seanfcarroll [release 0.22](https://github.com/stimulus-use/stimulus-use/releases/tag/v0.22.0) should completely correct your issue

Thanks for sharing your controller.
