### ISSUE TITLE
`useClickOutside`: Unexpected token 'export'

### ISSUE THREAD

**Issue by neckhair** [stimulus-use/stimulus-use#179]
I just upgraded stimulus-use in an application. Now I get the following error in my Jest tests:

```
  /app/node_modules/stimulus-use/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { useIntersection, IntersectionController } from './use-intersection/index';
...                          
    > 4 | import { useClickOutside } from "stimulus-use"
```

The issue seems to have been introduced in v0.25.0. The latest version before that one works. I am not familiar enough with all these JS magic happening. For me the diff between these versions does not seem to contain anything suspicious or an intended change of behaviour.

**Comment by marcoroth** [comment]
Hoi @neckhair 👋🏼 Sorry for getting to this just now. Were you able to resolve this in the meantime?

**Comment by marcoroth** [comment]
I'm going to close this, feel free to re-open this if you think it's still not working as expected, thank you!
