### ISSUE TITLE
useIntersection is unable to dispatch events

### ISSUE THREAD

**Issue by Cartman34** [stimulus-use/stimulus-use#180]
Hello,

In a dedicated controller, I am using

```
initialize() {
  console.log('Appearable', this.element);
  useIntersection(this, {
    dispatchEvent: true
  });
}
```
In a parent controller _frontend--search-loader_, I defined:
```
lastRow.dataset.action = "appear->frontend--search-loader#fetchNextPage";
```
lastRow is the last item of a visible list, but this item is never visible when loading it in DOM.
The purpose is to load the rest of the list when reaching this element.

The _appear_ event is never triggered by stimulus-use.

This is working properly if I dispatch the event by myself in the appear method.

```
appear() {
  console.log('Appear', this.element);
  this.dispatchEvent(this.element, 'appear');// Custom method to dispatch custom event
}
```

I may not know how to use properly this but I read all the manuals with no success...

**Comment by Sub-Xaero** [comment]
@Cartman34

By default the event name has the controller name [prefixed before it](https://github.com/stimulus-use/stimulus-use/blob/21a2e9877ed8c6cfc4d9459e945ff0dc0af404e2/src/support/index.ts#L12).  

It looks like you have an `appearable` controller you're doing this from? Try `data-action="appearable:appear->frontend--search-loader#fetchNextPage"`, or pass 
```
 useIntersection(this, {
    eventPrefix: false,
});
```

Dynamically mounting an action on the element i.e. `lastRow.dataset.action = "...";` might also be a bit of funky design pattern in Stimulus. So if you're still having trouble after trying the above, there might be something going wrong there.

**Comment by Cartman34** [comment]
Yes, it seems to be a PEBKAC, I am closing it. It appears I was lost in all manuals xD
Dynamically mounting action is working great for now, all stimulus features are reacting well to dynamic changes, this is awesome :)

Thank you for your quick & detailed help !

**Comment by Sub-Xaero** [comment]
In fairness, I don't think the prefixing of the controller name is documented very well, I'll open a PR to fix that if I get time 😊 

> Dynamically mounting action is working great for now, all stimulus features are reacting well to dynamic changes
Good to know! 

Glad I could help anyway, happy Stimulus-ing!
