### ISSUE TITLE
`useDispatch`: deprecate mixin

### ISSUE THREAD

**Issue by marcoroth** [stimulus-use/stimulus-use#206]
Since Stimulus now got a `dispatch()` function built-in (see: https://github.com/hotwired/stimulus/pull/302) we should think about deprecating (and later removing) the `useDispatch()` mixin from Stimulus Use. 

While it's still handy to have it included, so older apps can also use it, we should go through a deprecation cycle and start printing deprecation warnings to people still using it and let them know how they can migrate it.

Follow-up of #174

**Comment by adrienpoly** [comment]
I agree that this should be part of 1.00.
