### ISSUE TITLE
`useIntersection` and `appear@window`

### ISSUE THREAD

**Issue by ollietb** [stimulus-use/stimulus-use#218]
I can't really see the point of using the `appear@window` action if the controller has to have the function `appear` in it anyway. I'd like to skip the `appear` function in the controller and just use the action in the HTML.

eg
```js
export default class extends MainController {
  connect() {
    useIntersection(this, this.options);
  }
  trackView() {
    console.log('view');
  }
}
```

```
<div data-controller="ga" data-action="appear@window->ga#trackView">
</div>
```

But this doesn't seem possible, it only works for me when I specify the `appear()` function on the controller.

**Comment by marcoroth** [comment]
Hey @ollietb, thanks for opening this issue!

You can use just the event without specifying the `appear()` function in your controller.

In your case, you would need to pass in the `eventPrefix: false` option in order to get just the `appear` event name. Otherwise it's `[yourControllerIdentifier]:appear`.

**Comment by ollietb** [comment]
Thanks for replying. Ah, I missed that part of the documentation, and the example shows the use of `appear@window` so I assumed it would work like that.

**Comment by marcoroth** [comment]
Ah, you are right! That might be worth to add to the documentation, or at least change the event name in that example.

**Comment by marcoroth** [comment]
Also FWIW, since your `data-controller` and `data-action` are on the same element you should even be able to omit the `@window`, since the event is being dispatched on the controller element

**Comment by marcoroth** [comment]
I added some docs about this in a related `useIntersection()` PR I was working on (#217).

Going to close this one!
