### ISSUE TITLE
Deprecated Stimulus-1 Syntax

### ISSUE THREAD

**Issue by leon-vogt** [stimulus-use/stimulus-use#229]
Hi there,

When I run the "[building a cart counter with the dispatch helper"](https://stimulus-use.github.io/stimulus-use/#/use-dispatch?id=example-building-a-cart-counter-with-the-dispatch-helper)  example, I get a Stimulus warning for using Stimulus-1 syntax:

![stimulus-use-target-deprecation-warning](https://user-images.githubusercontent.com/17851143/197607108-391437b2-1985-48d4-8dcf-9764540805da.png)

There is an [issue](https://github.com/stimulus-use/stimulus-use/issues/206) for `use-dispatch` which should mark `use-dispatch` as deprecated.
Just thought, as long as `use-dispatch` is still a part of stimulus-use, you might want to adjust the documentation in the following places:

- docs/application-controller.md:66
- docs/use-dispatch.md:92
- playground/index.html:31

Or is it this way, because stimulus-use wants to be backward compatible?
If not I would open a PR to update the doc.

**Comment by marcoroth** [comment]
Hey @leon-vogt, thanks for opening this issue!

This "issue" is independent from #206.

The old syntax is still around because we actually never updated it. If you want you can happily open a separate Pull Request to update the targets to the new Stimulus 2 syntax.

**Comment by leon-vogt** [comment]
Hi @marcoroth, thanks for your reply and explanation!

I will open a small PR to update the Stimulus syntax.
