### ISSUE TITLE
`useDebounce` sometimes clears event.params

### ISSUE THREAD

**Issue by sc0ttman** [stimulus-use/stimulus-use#251]
A debounced action by itself seems to leave the params intact, however when combined with a global click listener, something is causing the params to be removed.

Please see the following repro: https://jsbin.com/tevawal/edit?html,console,output

Clicking on any of the like buttons in the example should output the action params, however they are currently undefined.
If you remove the global action: `click@window->menu#closeOnClickOutside` and click the buttons, they will output the correct param data.

I can access them using `event.target.dataset` however that is a workaround.

Any help would be greatly appreciated 👍

**Comment by marcoroth** [comment]
Hey @sc0ttman, thanks for opening this issue and for providing repro! 

This was a truly weird scenario! But I've figured it out. Ironically it's actually a bug in Stimulus itself. I'll let you know here once I've opened the pull request.

**Comment by sc0ttman** [comment]
Thanks @marcoroth 👍

**Comment by marcoroth** [comment]
I decided to fix it here in stimulus-use instead, see #252. I'm also going to publish `0.51.2` momentarily.

**Comment by marcoroth** [comment]
@all-contributors add @sc0ttman for bug
