### ISSUE TITLE
Use Object.defineProperty to copy getters onto controller

### ISSUE THREAD

**Issue by daun** [stimulus-use/stimulus-use#26]
`useApplication` adds two getters to the controller, `isPreview` and `csrfToken`. However, it uses `Object.assign` to do that, which won't copy them as getters but as primitives, reflecting the value at the point of assignment.

Using `Object.defineProperty` **will** copy them over as getters. See [this StackOverflow comment](https://stackoverflow.com/a/45772229/3759615) for details.

Simplified example:

```js
const instances = new Set()

export default (controller) => {

  Object.defineProperty(controller, 'instances', {
    get() {
      return [...instances]
    }
  })

  Object.assign(controller, {
    connect() {
      instances.add(this)
    },
    disconnect() {
      instances.delete(this)
    }
  })
}
```

**Comment by adrienpoly** [comment]
Thanks this is a very valid point. Feel free to submit a PR or I will look into correcting it

**Comment by daun** [comment]
I'd love to submit a PR, but I'm not a typescript person and have none of the tooling set up. Just thought I'd let you know.

**Comment by adrienpoly** [comment]
@all-contributors add @daun to bug
