### ISSUE TITLE
ESLint failure upgrading to 0.52.0

### ISSUE THREAD

**Issue by wooly** [stimulus-use/stimulus-use#282]
Hi there,

Probably something super minor, but I'm following the upgrade instructions for changing the useHotkeys import here: https://stimulus-use.github.io/stimulus-use/#/use-hotkeys?id=importing-the-behavior and I'm now getting failures in ESLint for the `import/no-unresolved` rule:

`error  Unable to resolve path to module 'stimulus-use/hotkeys'`

I've had a look at the no-unresolved configuration options but can't see anything that would be relevant. I'm unsure if I'm just holding it wrong!

**Comment by marcoroth** [comment]
Hey @wooly, thank you for bringing this up!

To be honest, I'm not sure what's causing this. But after reading on it a bit it seems like it could be related to webpack and it's config. Are you using webpack by any chance?

**Comment by marcoroth** [comment]
Or maybe it's actually just `eslint` itself which doesn't understand export-maps (which is what `stimulus-use/hotkeys` is relying on). 

Looking at https://github.com/import-js/eslint-plugin-import it seems like this might be necessary for eslint to understand "imports/exports fields support in package.json".

It might also just be a matter of updating eslint and its plugins to newer versions so it understands the modern syntax.

**Comment by wooly** [comment]
Hi @marcoroth, thanks for the quick response!

After digging a bit deeper into this, it looks like there's an open issue on the eslint-plugin-import repo here: https://github.com/import-js/eslint-plugin-import/issues/1810 that's been open for a while. I'll find a workaround, no worries.

Since this isn't really an issue with stimulus-use, I'm happy to close!

**Comment by wooly** [comment]
Thank you, will check it out!
