### ISSUE TITLE
Create a Polyfill package

### ISSUE THREAD

**Issue by adrienpoly** [stimulus-use/stimulus-use#3]
- https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
- https://www.npmjs.com/package/intersection-observer-polyfill
- https://www.npmjs.com/package/resize-observer-polyfill

**Comment by Matts** [comment]
Weird thing is, for some reason babel with "browserlist": { "IE 11" } does not actually transform the stimulus-use classes. So yes we need polyfill, but also need to figure out why these are not being transformed

**Comment by adrienpoly** [comment]
Interesting.....

I have a basic setup for Saucelabs to test against various browser. I didn't had time to play a lot with it yet. If you feel like it feel free to open a PR with II11 enabled in the Saucelabs config. This will at least run the CI and hopefully reproduce your bug.

**Comment by Matts** [comment]
@adrienpoly see #130

**Comment by Matts** [comment]
This one works for the custom event:
https://www.npmjs.com/package/custom-event-polyfill

**Comment by Matts** [comment]
Just so you know. The https://www.npmjs.com/package/intersection-observer-polyfill polyfill does NOT work.
Rather use the polyfill already noted within the stimulus-sue documentation (w3c) https://www.npmjs.com/package/intersection-observer

**Comment by adrienpoly** [comment]
:pray thanks @Matts for confirming this

**Comment by marcoroth** [comment]
I'm wondering if we still should ship an "official" Stimulus Use polyfill package since Stimulus 3+ doesn't ship polyfills anymore

/cc @adrienpoly

**Comment by adrienpoly** [comment]
Let's forget about that
