### ISSUE TITLE
Documentation for `useIntersection` is ahead of published version

### ISSUE THREAD

**Issue by Eldzej** [stimulus-use/stimulus-use#390]
Not sure what the policy for publishing new versions to NPM etc. is in this repository, but as of now, the documentation for `useIntersection` contains code that does not work in current version as result of #371  (0.52.0, which is what is available everywhere does not contain these changes yet)

**Comment by marcoroth** [comment]
All of the changes should be published, so I'm going to close this. Feel free to re-open if you still something that doesn't look right, thank you!
