### ISSUE TITLE
umd format is not working in browser with umd format 'stimulus'

### ISSUE THREAD

**Issue by lidqqq** [stimulus-use/stimulus-use#41]
Hi 🦖 

I found an error when I try to use this package in browser with umd format.

Repl code is below.

```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://unpkg.com/stimulus@1.1.1/dist/stimulus.umd.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/stimulus-use@0.12.0/dist/index.umd.js" crossorigin="anonymous"></script>
    <script>console.log(window.stimulusUse)</script>
</head>
<body>
</body>
</html>
```

I've tried to investigate, then found that `stimulus` umd js [expose the stimulus object](https://unpkg.com/stimulus@1.1.1/dist/stimulus.umd.js#:~:text=global.Stimulus) to 'window.Stimulus', but `stimulus-use` umd js try to use `window.stimulus` to invoke factory method.
https://unpkg.com/stimulus-use@0.12.0/dist/index.umd.js#:~:text=e.stimulus

That's why `undefined.Controller` cause a Error.

<img width="999" alt="スクリーンショット 2020-09-02 17 55 49" src="https://user-images.githubusercontent.com/39523918/91963078-5e13b700-ed48-11ea-9565-923ec3897195.png">
<img width="413" alt="スクリーンショット 2020-09-02 17 56 01" src="https://user-images.githubusercontent.com/39523918/91963082-5fdd7a80-ed48-11ea-8767-d1258fc8a3d4.png">

Is there anything we can do to resolve that? 🌵

**Comment by adrienpoly** [comment]
can you try the latest release 0.12.1 it should fix this

**Comment by adrienpoly** [comment]
The UMD object is `StimulusUse` capital I have changed it to be consistent with Stimulus
so in your example you will need to update it too

**Comment by lidqqq** [comment]
@adrienpoly 
Thanks for quick reply and modification!! 🏎️ 

It seems like working correctly!!
<img width="999" alt="スクリーンショット 2020-09-02 17 55 49" src="https://user-images.githubusercontent.com/39523918/91966160-71c11c80-ed4c-11ea-8e1e-41015e67d56a.png">
<img width="464" alt="スクリーンショット 2020-09-02 18 43 17" src="https://user-images.githubusercontent.com/39523918/91966225-843b5600-ed4c-11ea-95fa-eea44f11d2ef.png">
![スクリーンショット 2020-09-02 18 44 02](https://user-images.githubusercontent.com/39523918/91966228-856c8300-ed4c-11ea-8777-aeb80b234b14.png)

**Comment by adrienpoly** [comment]
Excellent thanks for the report

**Comment by adrienpoly** [comment]
@all-contributtors add @lidqqq to bug

**Comment by adrienpoly** [comment]
@all-contributors add @lidqqq to bug
