### ISSUE TITLE
[bug] Duplication name properties are never called in controller

### ISSUE THREAD

**Issue by lidqqq** [stimulus-use/stimulus-use#45]
Hi 🎃 

I found a bug that duplication name properties are never called in controller object because `Object.assign` break original object.

For example, readme's sample code is below.

```js
...
  connect() {
    useIntersection(this)
    useResize(this)
  }
...
```

And, we change some code in stimulus-use codes.

```js
// src/use-resize/use-resize.ts
    unObserve() {
      console.log('ResizeObserver: unObserve')
      this.observer.unobserve(targetElement)
    },
```

```js
// src/use-intersection/use-intersection.ts
    unObserve() {
      console.log('IntersectionObserver: unObserve')
      this.observer.unobserve(targetElement)
    },
```

Next, remove element which is connected with `useIntersection` and `useResize` mixins function, then `unObserve` function is called twice which is __connected later__(in this code, `useResize` is connected later).

<img width="738" alt="スクリーンショット 2020-09-04 9 22 17" src="https://user-images.githubusercontent.com/39523918/92185939-24e65e80-ee90-11ea-8dae-7f64f0b7f514.png">

This behavior have a risk of memory leak because call back function would be never cleared.

One way we have to fix this problem is to name methods by using a Symbol object. Symbol is not conflict its same name that's why we can use same name in mixin functions between mixins functions each other.

Or, we don't merge observe mixin functions to original controller object.

However, this procedure which add mixin function to original controller object is written in [betterstimulus](https://www.betterstimulus.com/architecture/mixins.html), so I'm confused this approach are well known in stimulus community? 

What do you think about it ? 👀

**Comment by adrienpoly** [comment]
Hello 

I have open a PR #46 with a solution by renaming the observers.
Could you elaborate on your suggestion about symbols this seems interesting but not sure how to implement it

Thanks

**Comment by lidqqq** [comment]
@adrienpoly 
Thanks for response !!

I just thought that we could use `Symbol` like below,

```typescript
const observe = Symbol(`observe`);
const observer = Symbol(`observer`);
const unObserve = Symbol(`unObserve`);
...
  Object.assign(controller, {
    [observer]: new IntersectionObserver(callback, options),
    [observe]: function () {
      this[observer].observe(targetElement);
    },
    [unObserve]: function () {
      console.log('IntersectionObserver: unObserve');
      this[observer].unobserve(targetElement);
    },
    disconnect: function () {
      this[unObserve]();
      controllerDisconnect();
    },
  });
  controller[observe]();
```

`Symbol` is not same each other even the same value.

```js
const obj = {};
const fn1 = Symbol('fn');
const fn2 = Symbol('fn');
obj[fn1] = () => 1;
obj[fn2] = () => 2;
console.log(obj[fn1]());
console.log(obj[fn2]());
// 1
// 2
```

That's why we could use same `observe` symbol in different mixin functions 👍

**Comment by adrienpoly** [comment]
This is a very interesting approach

And this brought some more question 

Let say that I have a controller with 2 behaviors

```js
...
connect() {
    useIntersection(this)
    useResize(this)
  }
...
```

With your suggestion it would work but calling `this.observe()` and `this.unobserve()` within the controller would be ambiguous. 

On the other side my proposal is not perfect neither. Assuming down the road we would want to have multiple call within the same controller to a mixin 

```js
...
  connect() {
    useIntersection(this, {element: el1 })
    useIntersection(this, {element: el2 })
  }
...
```
Then there is no way to call this.unobserveIntersection() as it will only stop the second one.

(This particular example does not really represent a viable use case but I have a few idea where down the road it could be required to add multiple identical mixin to the same controller)


My suggestion would be to update the overall API with the following pattern

internally stop assigning observe/unobserve to the controller

```js
//use-intersection.ts
... 
  const controllerDisconnect = controller.disconnect.bind(controller)

  const observer = new IntersectionObserver(callback, options)

  const observe = () => {
    observer.observe(targetElement)
  }

  const unobserve = () => {
    observer.unobserve(targetElement)
  }

  Object.assign(controller, {
    isVisible: false,
    disconnect() {
      unobserve()
      controllerDisconnect()
    },
  })
  observe()

  return { observe, unobserve }
}
```

If needed then the observe/unobserve functions are available with in the returned object of the mixin function 

```js
...
connect() {
    const { observe, unobserve } = useIntersection(this)
  }
...
```

Thanks for raising this point I think it is an important aspect to cover before 1.0

**Comment by lidqqq** [comment]
@adrienpoly 

> My suggestion would be to update the overall API with the following pattern

That's a great idea! 🥇 

If I add one point, I think returned objects should be `array` because Destructuring Assignment isn't able to change property name.

```js
// object
connect() {
    const { observe, unobserve } = useIntersection(this)
    const { observe, unobserve } = useResize(this) // <- Uncaught SyntaxError: Identifier 'observe' has already been declared
  }
// array
connect() {
    const [observeIntersection, unobserveIntersection] = useIntersection(this)
    const [observeResize, unobserveResize] = useResize(this) // 👍 
  }
```

The point of my suggestion is __not__ merging properties to original controller unless they're stored and invoked by __same name__ mixin function like a `disconnect` function or they use `Symbol` to identical own name to avoid conflicting property names. 🌵

**Comment by adrienpoly** [comment]
Perfect 🎉
